/* Generated By:JJTree: Do not edit this line. JSSPHtml.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=JSSP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.ss.parse;

public
class JSSPHtml extends AbstractNode {
  public JSSPHtml(int id) {
    super(id);
  }

  public JSSPHtml(JSSPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSSPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a5516c8a236e91b34f52a10698700fe8 (do not edit this line) */
