/* Generated By:JJTree&JavaCC: Do not edit this line. JSSPParserConstants.java */
package org.descripter.js.ss.parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JSSPParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LF = 1;
  /** RegularExpression Id. */
  int CR = 2;
  /** RegularExpression Id. */
  int LS = 3;
  /** RegularExpression Id. */
  int PS = 4;
  /** RegularExpression Id. */
  int SCRIPT = 8;
  /** RegularExpression Id. */
  int DOUBLE_STRING = 9;
  /** RegularExpression Id. */
  int SINGLE_STRING = 10;
  /** RegularExpression Id. */
  int HTML = 11;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SCRIPT = 1;
  /** Lexical state. */
  int IN_DOUBLE_STRING = 2;
  /** Lexical state. */
  int IN_SINGLE_STRING = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\u2028\"",
    "\"\\u2029\"",
    "\"<%\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"%>\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "<HTML>",
    "<token of kind 12>",
  };

}
