/* Generated By:JJTree: Do not edit this line. JSSPPage.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=JSSP,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.ss.parse;

public
class JSSPPage extends AbstractNode {
  public JSSPPage(int id) {
    super(id);
  }

  public JSSPPage(JSSPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSSPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=41faac7beaf50f793c8cdd138479acd7 (do not edit this line) */
