/* Generated By:JavaCC: Do not edit this line. JSSPParserTreeConstants.java Version 5.0 */
package org.descripter.js.ss.parse;

public interface JSSPParserTreeConstants
{
  public int JJTPAGE = 0;
  public int JJTSCRIPT = 1;
  public int JJTHTML = 2;


  public String[] jjtNodeName = {
    "Page",
    "Script",
    "Html",
  };
}
/* JavaCC - OriginalChecksum=629e6e1d42cd8622bd662edf917552fa (do not edit this line) */
