/* Generated By:JavaCC: Do not edit this line. JSSPParserVisitor.java Version 5.0 */
package org.descripter.js.ss.parse;

public interface JSSPParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(JSSPPage node, Object data);
  public Object visit(JSSPScript node, Object data);
  public Object visit(JSSPHtml node, Object data);
}
/* JavaCC - OriginalChecksum=ab1d1bde71a521dbe4a18c47a45ee396 (do not edit this line) */
