/* Generated By:JJTree: Do not edit this line. ECMAOrOperation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMAOrOperation extends AbstractNode {
  public ECMAOrOperation(int id) {
    super(id);
  }

  public ECMAOrOperation(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=28c9edd96de81a9f814afaa4f292f8dc (do not edit this line) */
