/* Generated By:JJTree: Do not edit this line. ECMAAssignmentExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMAAssignmentExpression extends AbstractNode {
  public ECMAAssignmentExpression(int id) {
    super(id);
  }

  public ECMAAssignmentExpression(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=667ffbb1097952e0d5aabc38860b72e7 (do not edit this line) */
