/* Generated By:JJTree: Do not edit this line. ECMACaseBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMACaseBlock extends AbstractNode {
  public ECMACaseBlock(int id) {
    super(id);
  }

  public ECMACaseBlock(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=085ec7a628fe98ff79b1f2ce11baa529 (do not edit this line) */
