/* Generated By:JJTree: Do not edit this line. ECMANewOperation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMANewOperation extends AbstractNode {
  public ECMANewOperation(int id) {
    super(id);
  }

  public ECMANewOperation(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a5aa5fa0e91f046d8cdad19509a63d72 (do not edit this line) */
