/* Generated By:JJTree: Do not edit this line. ECMAFormalParameterList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMAFormalParameterList extends AbstractNode {
  public ECMAFormalParameterList(int id) {
    super(id);
  }

  public ECMAFormalParameterList(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ed4ae7bb5edb04cdbacd257aedac2ac0 (do not edit this line) */
