/* Generated By:JJTree: Do not edit this line. ECMAArrayAccessor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMAArrayAccessor extends AbstractNode {
  public ECMAArrayAccessor(int id) {
    super(id);
  }

  public ECMAArrayAccessor(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ec18a57501ad7821ba73f528b8a196c0 (do not edit this line) */
