/* Generated By:JJTree: Do not edit this line. ECMAMemberAccessor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMAMemberAccessor extends AbstractNode {
  public ECMAMemberAccessor(int id) {
    super(id);
  }

  public ECMAMemberAccessor(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=69171dcc99a3d19186c7e5dfdfe9f053 (do not edit this line) */
