/* Generated By:JJTree: Do not edit this line. ECMAVariableDeclarationList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMAVariableDeclarationList extends AbstractNode {
  public ECMAVariableDeclarationList(int id) {
    super(id);
  }

  public ECMAVariableDeclarationList(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=db3c8680a393cd2b694328433f836429 (do not edit this line) */
