/* Generated By:JJTree: Do not edit this line. ECMALabelledStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMALabelledStatement extends AbstractNode {
  public ECMALabelledStatement(int id) {
    super(id);
  }

  public ECMALabelledStatement(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bd48e259d8d20369c45bfc8cb5e198f6 (do not edit this line) */
