/* Generated By:JJTree: Do not edit this line. ECMAEmptyExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMAEmptyExpression extends AbstractNode {
  public ECMAEmptyExpression(int id) {
    super(id);
  }

  public ECMAEmptyExpression(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1c76d5cd7ab5e35780b52ebec395d35b (do not edit this line) */
