/* Generated By:JJTree: Do not edit this line. ECMAVariableDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMAVariableDeclaration extends AbstractNode {
  public ECMAVariableDeclaration(int id) {
    super(id);
  }

  public ECMAVariableDeclaration(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=92a38bba28007f3a0778a1970683146f (do not edit this line) */
