/* Generated By:JJTree: Do not edit this line. ECMAArrayLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMAArrayLiteral extends AbstractNode {
  public ECMAArrayLiteral(int id) {
    super(id);
  }

  public ECMAArrayLiteral(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=419e063e7a46f6c8739f24501df15e62 (do not edit this line) */
