/* Generated By:JJTree: Do not edit this line. ECMAReturnStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMAReturnStatement extends AbstractNode {
  public ECMAReturnStatement(int id) {
    super(id);
  }

  public ECMAReturnStatement(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fc55e856eaf638cf62aa116ab8bae8dd (do not edit this line) */
