/* Generated By:JJTree: Do not edit this line. ECMAPostfixExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMAPostfixExpression extends AbstractNode {
  public ECMAPostfixExpression(int id) {
    super(id);
  }

  public ECMAPostfixExpression(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cfe01a9f02e6dbdf27d2b62b096c9eff (do not edit this line) */
