/* Generated By:JJTree: Do not edit this line. ECMAIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMAIdentifier extends AbstractNode {
  public ECMAIdentifier(int id) {
    super(id);
  }

  public ECMAIdentifier(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c1cb1f80e38c0fc5dfb4d8688fbd6455 (do not edit this line) */
