/* Generated By:JJTree: Do not edit this line. ECMABinaryOperation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ECMA,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.descripter.js.parse;

public
class ECMABinaryOperation extends AbstractNode {
  public ECMABinaryOperation(int id) {
    super(id);
  }

  public ECMABinaryOperation(JSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=684c5c3f371f97bedc02ca9ce42d031f (do not edit this line) */
