/* Generated By:JavaCC: Do not edit this line. JSParserTreeConstants.java Version 5.0 */
package org.descripter.js.parse;

public interface JSParserTreeConstants
{
  public int JJTLITERAL = 0;
  public int JJTVOID = 1;
  public int JJTTHISREFERENCE = 2;
  public int JJTGROUP = 3;
  public int JJTARRAYLITERAL = 4;
  public int JJTOBJECTLITERAL = 5;
  public int JJTPROPERTYASSIGNMENT = 6;
  public int JJTNEWOPERATION = 7;
  public int JJTACCESS = 8;
  public int JJTALLOCATION = 9;
  public int JJTARRAYACCESSOR = 10;
  public int JJTMEMBERACCESSOR = 11;
  public int JJTARGUMENTS = 12;
  public int JJTPOSTFIXEXPRESSION = 13;
  public int JJTOPERATOR = 14;
  public int JJTUNARYEXPRESSION = 15;
  public int JJTBINARYOPERATION = 16;
  public int JJTANDOPERATION = 17;
  public int JJTOROPERATION = 18;
  public int JJTCONDITIONALEXPRESSION = 19;
  public int JJTASSIGNMENTEXPRESSION = 20;
  public int JJTCOMMAEXPRESSION = 21;
  public int JJTJAVASTATEMENT = 22;
  public int JJTBLOCK = 23;
  public int JJTSTATEMENTLIST = 24;
  public int JJTVARIABLESTATEMENT = 25;
  public int JJTVARIABLEDECLARATIONLIST = 26;
  public int JJTVARIABLEDECLARATION = 27;
  public int JJTEMPTYEXPRESSION = 28;
  public int JJTEXPRESSIONSTATEMENT = 29;
  public int JJTIFSTATEMENT = 30;
  public int JJTDOWHILESTATEMENT = 31;
  public int JJTWHILESTATEMENT = 32;
  public int JJTFORSTATEMENT = 33;
  public int JJTFORVARSTATEMENT = 34;
  public int JJTFORVARINSTATEMENT = 35;
  public int JJTFORINSTATEMENT = 36;
  public int JJTCONTINUESTATEMENT = 37;
  public int JJTBREAKSTATEMENT = 38;
  public int JJTRETURNSTATEMENT = 39;
  public int JJTWITHSTATEMENT = 40;
  public int JJTSWITCHSTATEMENT = 41;
  public int JJTCASEBLOCK = 42;
  public int JJTCASECLAUSE = 43;
  public int JJTCASE = 44;
  public int JJTLABELLEDSTATEMENT = 45;
  public int JJTTHROWSTATEMENT = 46;
  public int JJTTRYSTATEMENT = 47;
  public int JJTCATCH = 48;
  public int JJTFINALLY = 49;
  public int JJTDEBUGGERSTATEMENT = 50;
  public int JJTFUNCTIONDECLARATION = 51;
  public int JJTFORMALPARAMETERLIST = 52;
  public int JJTFUNCTIONEXPRESSION = 53;
  public int JJTPROGRAM = 54;
  public int JJTIDENTIFIER = 55;


  public String[] jjtNodeName = {
    "Literal",
    "void",
    "ThisReference",
    "Group",
    "ArrayLiteral",
    "ObjectLiteral",
    "PropertyAssignment",
    "NewOperation",
    "Access",
    "Allocation",
    "ArrayAccessor",
    "MemberAccessor",
    "Arguments",
    "PostfixExpression",
    "Operator",
    "UnaryExpression",
    "BinaryOperation",
    "AndOperation",
    "OrOperation",
    "ConditionalExpression",
    "AssignmentExpression",
    "CommaExpression",
    "JavaStatement",
    "Block",
    "StatementList",
    "VariableStatement",
    "VariableDeclarationList",
    "VariableDeclaration",
    "EmptyExpression",
    "ExpressionStatement",
    "IfStatement",
    "DoWhileStatement",
    "WhileStatement",
    "ForStatement",
    "ForVarStatement",
    "ForVarInStatement",
    "ForInStatement",
    "ContinueStatement",
    "BreakStatement",
    "ReturnStatement",
    "WithStatement",
    "SwitchStatement",
    "CaseBlock",
    "CaseClause",
    "Case",
    "LabelledStatement",
    "ThrowStatement",
    "TryStatement",
    "Catch",
    "Finally",
    "DebuggerStatement",
    "FunctionDeclaration",
    "FormalParameterList",
    "FunctionExpression",
    "Program",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=da98f2934378114bff86b2be8b73b59d (do not edit this line) */
