/* Generated By:JavaCC: Do not edit this line. JSParserVisitor.java Version 5.0 */
package org.descripter.js.parse;

public interface JSParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ECMALiteral node, Object data);
  public Object visit(ECMAThisReference node, Object data);
  public Object visit(ECMAGroup node, Object data);
  public Object visit(ECMAArrayLiteral node, Object data);
  public Object visit(ECMAObjectLiteral node, Object data);
  public Object visit(ECMAPropertyAssignment node, Object data);
  public Object visit(ECMANewOperation node, Object data);
  public Object visit(ECMAAccess node, Object data);
  public Object visit(ECMAAllocation node, Object data);
  public Object visit(ECMAArrayAccessor node, Object data);
  public Object visit(ECMAMemberAccessor node, Object data);
  public Object visit(ECMAArguments node, Object data);
  public Object visit(ECMAPostfixExpression node, Object data);
  public Object visit(ECMAOperator node, Object data);
  public Object visit(ECMAUnaryExpression node, Object data);
  public Object visit(ECMABinaryOperation node, Object data);
  public Object visit(ECMAAndOperation node, Object data);
  public Object visit(ECMAOrOperation node, Object data);
  public Object visit(ECMAConditionalExpression node, Object data);
  public Object visit(ECMAAssignmentExpression node, Object data);
  public Object visit(ECMACommaExpression node, Object data);
  public Object visit(ECMAJavaStatement node, Object data);
  public Object visit(ECMABlock node, Object data);
  public Object visit(ECMAStatementList node, Object data);
  public Object visit(ECMAVariableStatement node, Object data);
  public Object visit(ECMAVariableDeclarationList node, Object data);
  public Object visit(ECMAVariableDeclaration node, Object data);
  public Object visit(ECMAEmptyExpression node, Object data);
  public Object visit(ECMAExpressionStatement node, Object data);
  public Object visit(ECMAIfStatement node, Object data);
  public Object visit(ECMADoWhileStatement node, Object data);
  public Object visit(ECMAWhileStatement node, Object data);
  public Object visit(ECMAForStatement node, Object data);
  public Object visit(ECMAForVarStatement node, Object data);
  public Object visit(ECMAForVarInStatement node, Object data);
  public Object visit(ECMAForInStatement node, Object data);
  public Object visit(ECMAContinueStatement node, Object data);
  public Object visit(ECMABreakStatement node, Object data);
  public Object visit(ECMAReturnStatement node, Object data);
  public Object visit(ECMAWithStatement node, Object data);
  public Object visit(ECMASwitchStatement node, Object data);
  public Object visit(ECMACaseBlock node, Object data);
  public Object visit(ECMACaseClause node, Object data);
  public Object visit(ECMACase node, Object data);
  public Object visit(ECMALabelledStatement node, Object data);
  public Object visit(ECMAThrowStatement node, Object data);
  public Object visit(ECMATryStatement node, Object data);
  public Object visit(ECMACatch node, Object data);
  public Object visit(ECMAFinally node, Object data);
  public Object visit(ECMADebuggerStatement node, Object data);
  public Object visit(ECMAFunctionDeclaration node, Object data);
  public Object visit(ECMAFormalParameterList node, Object data);
  public Object visit(ECMAFunctionExpression node, Object data);
  public Object visit(ECMAProgram node, Object data);
  public Object visit(ECMAIdentifier node, Object data);
}
/* JavaCC - OriginalChecksum=bd2553def4769f4345e55573c598d758 (do not edit this line) */
